2022.27; adapt docs for new homepage

diff --git a/makearch b/makearch
--- a/makearch
+++ b/makearch
@@ -44,6 +44,15 @@ then
 	$exit 9
     fi
 
+    release=`echo $fullrelease | sed -e 's,.* ,,'`
+    if egrep "$release" src/version.h > /dev/null
+    then
+	true
+    else
+	echo "$error wrong VERSION information in src/version.h $normal" >&2
+	$exit 9
+    fi
+
     if grep "$version (`LC_ALL=C date +%B\ %Y`)" doc/changes.html > /dev/null
     then
 	true
